Fix tbblib ISO C++17 does not allow dynamic exception specifications
On Ubuntu 22.04:

```
parsecmgmt -a build -p tbblib
```

would fail with error:

```
../../src/tbbmalloc/proxy.cpp:160:32: error: ISO C++17 does not allow dynamic exception specifications
```

Explicit dynamic exception specification has been removed in C++17, which
at some point became the default standard version for g++

The build system did not specify an explicit standard version, and so at
one point C++17 became the default and things broke.

Also set an explicit standard version to prevent future breaks like this.

Fix #13